/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef RooCeMPdf_h_
#define RooCeMPdf_h_

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooCeMPdf : public RooAbsPdf {
public:
  RooCeMPdf() {} ; 
  RooCeMPdf(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _eMax,
	    RooAbsReal& _me,
	    RooAbsReal& _alpha
	    ) :
    RooAbsPdf(name,title), 
    x("x","x",this,_x),
    eMax("eMax","eMax",this,_eMax),
    me("me","me",this,_me),
    alpha("alpha","alpha",this,_alpha)
  { }

  RooCeMPdf(const RooCeMPdf& other, const char* name=0) :
    RooAbsPdf(other,name), 
    x("x",this,other.x),
    eMax("eMax",this,other.eMax),
    me("me",this,other.me),
    alpha("alpha",this,other.alpha)
  { }

  virtual TObject* clone(const char* newname) const { return new RooCeMPdf(*this,newname); }
  inline virtual ~RooCeMPdf() { }
  
protected:
  
  RooRealProxy x ;
  RooRealProxy eMax ;
  RooRealProxy me ;
  RooRealProxy alpha ;
  
  Double_t evaluate() const {
    double E = std::sqrt(x*x + me*me); // spectrum calculated with total energy, x is momentum
    double result = (1./eMax)*(alpha/(2*M_PI))*(log(4*E*E/me/me)-2.)*((E*E+eMax*eMax)/eMax/(eMax-E));
    if (result < 0) {
      result = 0;
    }
    return result;
  }
  
  
  ClassDef(RooCeMPdf,1) // Your description goes here...
};
 
#endif
