/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef RooRPCPdf_h_
#define RooRPCPdf_h_

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooRPCPdf : public RooAbsPdf {
public:
  RooRPCPdf() {} ; 
  RooRPCPdf(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _p0,
	    RooAbsReal& _p1,
	    RooAbsReal& _p2,
	    RooAbsReal& _p3,
	    RooAbsReal& _p4,
	    RooAbsReal& _p5
	    ) :
    RooAbsPdf(name,title), 
    x("x","x",this,_x),
    p0("p0","p0",this,_p0),
    p1("p1","p1",this,_p1),
    p2("p2","p2", this, _p2),
    p3("p3","p3", this,_p3),
    p4("p4","p4",this,_p4),
    p5("p5", "p5", this,_p5)

  { }

  RooRPCPdf(const RooRPCPdf& other, const char* name=0) :
    RooAbsPdf(other,name), 
    x("x",this,other.x),
    p0("p0",this,other.p0),
    p1("p1",this,other.p1),
    p2("p2", this, other.p2),
    p3("p3", this,other.p3),
    p4("p4",this,other.p4),
    p5("p5", this,other.p5)
  { }

  virtual TObject* clone(const char* newname) const { return new RooRPCPdf(*this,newname); }
  inline virtual ~RooRPCPdf() { }
  
protected:
  
  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;
  RooRealProxy p4 ;
  RooRealProxy p5;
  //TODO: wrap this around a Mu2e utility  
  Double_t evaluate() const {
    
    double E = std::sqrt(x*x + p2*p2); // spectrum calculated with total energy, x is momentum
    double result = pow(abs(p2-E),p0)*exp(-1*(abs(p2-p5*E))/p1)*(p3+p4*E);
    //double result = 1*pow((eMax-E),alpha)*exp(-1*(eMax-gamma*E)/tau)*(alpha*E);
    if (result < 0) {
      result = 0;
    }
    return result;
  }
  
  
  ClassDef(RooRPCPdf,1) // Your description goes here...
};
 
#endif
